export type {
  Profile,
  Exam,
  Question,
  Rubric,
  Submission,
  AiGradingResult,
  Grade,
  InstitutionType,
  Role,
  ExamStatus,
  QuestionType,
  ScoringType,
  FileType,
  OcrStatus,
  SubmissionStatus,
  AiModel,
  ConfidenceLevel,
} from "@/generated/prisma/client";
